### ISSUE TITLE
Build error - Manifest context variable unsupported

### ISSUE THREAD

**Issue by GameTapped** [britzl/manifestation#1]
https://github.com/britzl/manifestation/blob/10ead76ec7b5ec4032824b440a11cc558e4d2b85/index.html#L163 

https://github.com/britzl/manifestation/blob/10ead76ec7b5ec4032824b440a11cc558e4d2b85/index.html#L164 

Windows, Editor 2, building for Android causes build error.  (possibly affects others)

Removing the "d" from "excluded" and changing to "excludeLibs:"  and "excludeSymbols:" seems to fix.

**Comment by britzl** [comment]
Thanks! Fixed!
