### ISSUE TITLE
Update to work with 1.8.0

### ISSUE THREAD

**Issue by subsoap** [britzl/manifestation#11]
1.8.0

In order to support the feature of removing physics, we have now introduced two app manifest settings. If you are using a custom .appmanifest, and you wish to remove all physics, take note of these changes (or compare with a vanilla app manifest with physics removed):

      excludeLibs: [physics, Box2D, script_box2d]
      excludeSymbols: [ScriptBox2DExt]

**Comment by britzl** [comment]
This tool is not really useful anymore since we now support editing and creating app manifests from within Defold:

https://defold.com/manuals/app-manifest/

**Comment by subsoap** [comment]
> This tool is not really useful anymore since we now support editing and creating app manifests from within Defold:
> 
> https://defold.com/manuals/app-manifest/

Nice! I have been too distant to have noticed that. Should update the readme then to depreciate this and then archive the repo.

**Comment by subsoap** [comment]
Also important to edit this too since it's pointed to in many forum posts https://britzl.github.io/manifestation/
