### ISSUE TITLE
The size of web-js is still big, I think.

### ISSUE THREAD

**Issue by CocosGames** [britzl/manifestation#9]
What's added in version 1.2.170? Can it be excluded?

**Comment by CocosGames** [comment]
Do you have a list about all the symbols we can exclude?

**Comment by britzl** [comment]
We're updating Emscripten in version 1.2.178. The new version will result in a smaller engine size (https://github.com/defold/defold/pull/5416).

This project should contain a list of all symbols that can be excluded.

**Comment by CocosGames** [comment]
That's a great news.
